# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
