# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_dojo_ninja'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='des',
            field=models.TextField(default='des'),
            preserve_default=False,
        ),
    ]
